### ISSUE TITLE
Header clash during build on Ubuntu 22.04

### ISSUE THREAD

**Issue by billw1955** [USNavalResearchLaboratory/ospf-mdr#8]
Tried master and 63f0759

```
make[2]: Entering directory '/home/coreuser/Documents/ospf-mdr/zebra'
gcc -DHAVE_CONFIG_H -DSYSCONFDIR=\"/usr/local/etc/quagga/\" -DMULTIPATH_NUM=1 -I. -I.. -I.. -I.. -I../lib    -fPIE  -ggdb -MT test_main.o -MD -MP -MF .deps/test_main.Tpo -c -o test_main.o test_main.c
mv -f .deps/test_main.Tpo .deps/test_main.Po
gcc -DHAVE_CONFIG_H -DSYSCONFDIR=\"/usr/local/etc/quagga/\" -DMULTIPATH_NUM=1 -I. -I.. -I.. -I.. -I../lib    -fPIE  -ggdb -MT zebra_rib.o -MD -MP -MF .deps/zebra_rib.Tpo -c -o zebra_rib.o zebra_rib.c
mv -f .deps/zebra_rib.Tpo .deps/zebra_rib.Po
gcc -DHAVE_CONFIG_H -DSYSCONFDIR=\"/usr/local/etc/quagga/\" -DMULTIPATH_NUM=1 -I. -I.. -I.. -I.. -I../lib    -fPIE  -ggdb -MT interface.o -MD -MP -MF .deps/interface.Tpo -c -o interface.o interface.c
In file included from interface.c:37:
../zebra/rtadv.h:71:8: error: redefinition of ‘struct nd_opt_adv_interval’
   71 | struct nd_opt_adv_interval {   /* Advertisement interval option */
      |        ^~~~~~~~~~~~~~~~~~~
In file included from ../lib/zebra.h:211,
                 from interface.c:23:
/usr/include/netinet/icmp6.h:329:8: note: originally defined here
  329 | struct nd_opt_adv_interval
      |        ^~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:609: interface.o] Error 1
make[2]: Leaving directory '/home/coreuser/Documents/ospf-mdr/zebra'
make[1]: *** [Makefile:481: all-recursive] Error 1
make[1]: Leaving directory '/home/coreuser/Documents/ospf-mdr'
make: *** [Makefile:413: all] Error 2
```

```
6.2.0-1015-aws #15~22.04.1-Ubuntu SMP Fri Oct  6 21:37:24 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"

||/ Name           Version            Architecture Description
+++-==============-==================-============-===============================================================
ii  autoconf       2.71-2             all          automatic configure script builder
ii  automake       1:1.16.5-1.3       all          Tool for generating GNU Standards-compliant Makefiles
ii  gawk           1:5.1.0-1ubuntu0.1 amd64        GNU awk, a pattern scanning and processing language
ii  libtool        2.4.6-15build2     all          Generic library support script
ii  make           4.3-4.1build1      amd64        utility for directing compilation
ii  texinfo        6.8-4build1        amd64        Documentation system for on-line information and printed output
```

```
*   acaf5c4 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #6 from dpward/vtysh-extract-xpimd
|\
| * 640855d vtysh: Limit files in xpimd/ processed by extract.pl
* |   e7ab6a0 Merge pull request #5 from dpward/xpimd-static-assert
|\ \
| |/
|/|
| * 6dbc6ec xpimd: Rename macro static_assert() to x_static_assert()
|/
* 9d7bec5 packaging: Update rpm spec file to work on newer systems.
*   63f0759 Merge pull request #4 from hdznrrd/master
|\
| * 0a55487 Added extern
|/
* f21688c ospf6d: Update the next-best route before removing a route.
* 
```

**Comment by weston-nrl** [comment]
I'm not sure how you're building or what options you're using, but I cannot reproduce this error with default build options on up-to-date Ubuntu 22.04 using the latest code in master/HEAD.  I get no errors with this:

git clone https://github.com/USNavalResearchLaboratory/ospf-mdr.git
./bootstrap.sh
./configure
make

**Comment by billw1955** [comment]
Thank you for looking at this.

Are we starting from the same image?
```
# docker pull ubuntu:22.04
22.04: Pulling from library/ubuntu
Digest: sha256:2b7412e6465c3c7fc5bb21d3e6f1917c167358449fecac8176c6e496e5c1f05f
Status: Image is up to date for ubuntu:22.04
docker.io/library/ubuntu:22.04
```
I have to install multiple packages to get all the build tools in place, which you don't show.  Even git isn't in the image I get from docker.

**Comment by weston-nrl** [comment]
I was testing on an existing Ubuntu 22.04 installation with the latest updates.
