### PR TITLE
Added casts to support stricter type requirements in gcc 14.3.0

### PR DESCRIPTION
**Pull request by Kevlar**
Wanted to offer a quick patch to support stricter type requirements in gcc!

Let me know if you have any thoughts/questions.
-Kevin

### CODE REVIEW

**Comment by Kevlar** [comment]
@bebopagogo would you be able to look at this? I'm not sure who else to ping.

**Comment by FrancescElies** [comment]
I was just passing by and wanted to compile the project

when compiling with latest master you get
```
prefix.c: In function 'prefix_default':
prefix.c:920:31: error: passing argument 1 of 'prefix_ipv4_any' from incompatible pointer type [-Wincompatible-pointer-types]
  920 |       return prefix_ipv4_any (p);
      |                               ^
      |                               |
      |                               const struct prefix *
prefix.c:493:44: note: expected 'const struct prefix_ipv4 *' but argument is of type 'const struct prefix *'
  493 | prefix_ipv4_any (const struct prefix_ipv4 *p)
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^
prefix.c:925:35: error: passing argument 1 of 'prefix_ipv6_default' from incompatible pointer type [-Wincompatible-pointer-types]
  925 |       return prefix_ipv6_default (p);
      |                                   ^
      |                                   |
      |                                   const struct prefix *
prefix.c:908:48: note: expected 'const struct prefix_ipv6 *' but argument is of type 'const struct prefix *'
  908 | prefix_ipv6_default (const struct prefix_ipv6 *p)
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~^
```

I can confirm this PR allows you to build with `gcc (Debian 14.2.0-19) 14.2.0`
